# Generated by Django 5.1.7 on 2025-03-23 15:20

import auditApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditApp', '0005_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=auditApp.models.get_unique_hex_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
